# environment
env_name: 'CartPole-v1'
max_episode: 500
state_dim: None
action_dim: None

# algorithm
hidden_dim: 64
actor_lr: 0.0005
critic_lr: 0.001
gamma: 0.99
lambda_: 0.95
normalize: False
clip: 0.2
K_epoch: 4
batch_size: 64
entropy_coef: 0.01

# log
seed: 0
test_episode_interval: 10